### ISSUE TITLE
The Japanese version of 'Front-End-Design-Checklist

### ISSUE THREAD

**Issue by 53able** [thedaviddias/Front-End-Design-Checklist#11]
Hi @thedaviddias,

I'd like to translate 'Front-End-Design-Checklist' into Japanese. Is that OK with you?

The Japanese version link address is [Front-End-Design-Checklist](https://github.com/GameWith/Front-End-Design-Checklist).

Thanks!

**Comment by thedaviddias** [comment]
@53able I'm sorry, I forgot to answer you. Of course, feel free to translate the FEDC into Japanese 😉
