### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by mbiesiad** [thedaviddias/Front-End-Design-Checklist#13]
Hi, referring to #12 [PR](https://github.com/thedaviddias/Front-End-Design-Checklist/pull/12), here: https://github.com/mbiesiad/Front-End-Design-Checklist

is a Polish translation 🔥

@thedaviddias 
Best wishes

**Comment by coderbm1** [comment]
@thedaviddias some time has passed.. is it OK?

**Comment by coderbm1** [comment]
Closed, see #14
