### ISSUE TITLE
The chinese version of 'Front-End-Design-Checklist' 

### ISSUE THREAD

**Issue by JohnsenZhou** [thedaviddias/Front-End-Design-Checklist#5]
Hi @David,

The chinese version of 'Front-End-Design-Checklist' has been translated. The link address is [Front-End-Design-Checklist](https://github.com/JohnsenZhou/Front-End-Design-Checklist).

Thanks!

**Comment by thedaviddias** [comment]
Wahou! Thank you so much for all that work @JohnsenZhou! Adding the link on the README file.
