### ISSUE TITLE
Items Do Not Check Off When Clicked

### ISSUE THREAD

**Issue by stavvie34** [thedaviddias/Front-End-Design-Checklist#9]
## Expected Behavior
When clicked, each item should indicate that it has been checked off somehow.

## Current Behavior
For me, nothing happens. I get this error in the console though:

```js
Uncaught TypeError: Cannot read property 'setAttribute' of undefined | app.bundle.js:1 
    at e.value (app.bundle.js:1)
    at e.value (app.bundle.js:1)
    at app.bundle.js:1
    at NodeList.forEach (<anonymous>)
    at e.value (app.bundle.js:1)
    at new e (app.bundle.js:1)
    at Object.<anonymous> (app.bundle.js:1)
    at t (app.bundle.js:1)
    at Object.<anonymous> (app.bundle.js:1)
    at t (app.bundle.js:1)
```

## Steps to Reproduce

1. Use latest version of Chrome on Windows 10 laptop.
2. Navigate to https://frontenddesignchecklist.io/ in browser.
3. Click on any list item.

## GIF
*Note: Some items are already "checked" because I recorded the gif after I encountered the error for the first time.*

![alt text](https://imgur.com/download/43rXJz2 "Issue #1")

**Comment by thedaviddias** [comment]
Thanks @stavvie34 to point that out, I'll correct that ASAP.

**Comment by stavvie34** [comment]
@thedaviddias, no problem! I think the project as a whole is really cool. Good work.
